[package]
name = "dquic-h3"
version = "0.0.1"
edition.workspace = true
authors = ["youyuanwu@outlook.com"]
description = "dquic backend for h3-util (HTTP/3), used by tonic-h3 and axum-h3"
repository = "https://github.com/youyuanwu/quic-h3"
readme = "./README.md"
license = "MIT"
categories = ["web-programming", "network-programming"]
keywords = ["http", "h3", "quic"]

[lib]
test = false

[dependencies]
h3-util.workspace = true
h3-shim.workspace = true
dquic.workspace = true
hyper.workspace = true
bytes.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["time"] }
